security:
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
    encoders:
      AppBundle\Entity\AmlUser:
        algorithm: bcrypt
        cost: 12
        
    providers:
        amlog_db_provider:
            entity:
                class: AppBundle:AmlUser
                property: useName
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: amlog_db_provider
            logout:
                path: /logout
                target: /login            
            anonymous: ~
            form_login:
              login_path: login
              check_path: login
#            http_basic: ~
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/confirm/, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/admin, roles: ROLE_ADMIN}