security:
    providers:
        in_memory:
            memory:
              users:
                cubias:
                  password: $2y$12$e0dtMubkAz1aFhgyoiYQ/eQd9MQRrdyXiN605zeIAEGjACoEMzJQq
                  roles: 'ROLE_USER'
                admin:
                  password: $2y$12$sDz0jtAcnH0wGTPw0U.4QuiB.t1bf2rDTBf7Vl/DQ3EAvqqQZORA.
                  roles: 'ROLE_ADMIN'
    encoders:
      Symfony\Component\Security\Core\User\User:
        algorithm: bcrypt
        cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        main:
            anonymous: ~
            form_login:
              login_path: login
              check_path: login
              default_target_path: home
              always_use_default_target_path: true
#            http_basic: ~
    access_control:
        - { path: ^/temp, roles: ROLE_USER}